language: cpp

sudo: false

compiler:
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make && ./checkops
  - cd ..
  - mkdir -p /tmp/one
  - mkdir -p /tmp/two
  - ./build/encfs --extpass="echo test" --standard /tmp/one /tmp/two
  - ./test.sh

addons:

  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - cmake
      - libfuse-dev

