language: cpp

sudo: true

compiler:
  - clang

before_script:
  - sudo modprobe fuse
  - mkdir build
  - cd build
  - cmake ..

script:
  - make && ./checkops && cd .. && ./test.sh

addons:

  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - cmake
      - fuse
      - libfuse-dev
